### PR TITLE
Created new branch to catch up with master branch. 

### PR DESCRIPTION
**Pull request by emmariaolsson**
Branch contains additional: 
- GamePresenter, 
- GameView 
- ChoiceView

Instead of HelloWorld in the Home component, GamePresenter is displayed. To see Choice, one have to change game.phase = "choice" in GamePresenter mock data and change back to guessing/GameView with game.phase = "listen"

### CODE REVIEW

**Comment by LeoBergqvist** [comment]
Testat kod, några saker som ev inte fungerar:

* Kan ej connect:a till spotify (prompten kommer upp men efter man loggat in står det connect igen)
* Kan ej se gamepresenter presentera några kort. Kanske inte är tillagt än
* Gamepresenter laddar ej i home 

Övrig kod funkar, inloggning, starta/avsluta spel dra kort osv.

**Comment by johanmoritz** [comment]
Leo ser du inte GamePresenter i /firebase? Jag har flyttat den dit.

**Comment by axelmjohansson** [comment]
- Can connect to Spotify, but connect button is not gray:ed out after auth. Cannot play song.
- Changed URL path during a game, cannot re-enter the game (can bypass login screen, game ID is entered into the field, then only the sign out button is shown): TypeError: Cannot read property 'year' of undefined.
Upon signing out: TypeError: Cannot read property 'parentNode' of null
Upon signing in again, the same game ID is entered, and the same error is present --> cannot access game.

**Comment by LeoBergqvist** [comment]
> 
> 
> Leo ser du inte GamePresenter i /firebase? Jag har flyttat den dit.

Jo jag hitta :)

**Pull request merged**
